### ISSUE TITLE
Camera fails: Calibrating Auto Exposure

### ISSUE THREAD

**Issue by KidA-88** [sparkfun/SparkFun_HM01B0_Camera_ArduinoLibrary#3]
@oclyke 
I am currently trying to run the Example1_StopMotion code you provided here. It is already very helpful.

However, I get the following error in my console:

waiting for first frame
0
1
b'Turned on camera regulator\r\nCamera.begin() failed with code: 1\nCalibrating Auto Exposure...\r\n'
2
3
4
5
6
7
and so on

I could successfuly compile and upload sketch onto the edge board. I have my board connected via USB-C instead of UART as you envision it in your example but this does not seem to be the problem. Do you have any idea what could cause this problem?

That being said, this example already is quite useful. Without it, I would be hopelessly lost. Thanks.

Best
Jan

**Comment by peepo** [comment]
Jan,
I did not provide the code,

I created an enhancement request: #1 
asking for more information, 
like you.

@oclyke is the party.

**Comment by KidA-88** [comment]
Of course, sorry, my bad. I corrected the post :)

**Comment by tony56a** [comment]
Seems like it failed somewhere [here](https://github.com/sparkfun/SparkFun_HM01B0_Camera_ArduinoLibrary/blob/master/src/hm01b0_arduino.cpp#L35), any chance you can add some `Serial.println` calls to see where it failed?

**Comment by KidA-88** [comment]
I think you are right. Given the error code (1) it must be line 45, i.e. the model id throws an error.
Luckily, I ordered two hm01b0 camera modules. I tried the other one and it works. Given time constraints, I will pragmatically continue with this model.
Thanks in any case though!

**Comment by tony56a** [comment]
NP, as a FYI though, if you're using one of the sparkfun connector boards, looking at the [datasheet for the camera](https://cdn.sparkfun.com/assets/b/3/e/8/e/HM01B0-MNA-Datasheet.pdf) and some of the relevant boards with the connector ([micromod as an example](https://cdn.sparkfun.com/assets/1/f/9/5/f/16400_SparkFun_MicroMod_Machine_Learning_Carrier_Board_Schematic.pdf)), it seems like the IO voltage is being set to 1.8V, and that may cause some issues as the other pins are still set to a 3.3v logic level.

(it did on mine, I had to remove the voltage regulator to get around a weird issue with the camera not actually allowing the camera mode register to be set, but the ID read/most of the configuration seemed to be fine). The other camera module might be impacted by this as well.

**Comment by mjs513** [comment]
Has this issue been resolved yet.

I just got a MicroMod Machine Learning Carrier board with the Artemis processor board along with the HB01B0 camera and its still getting stuck on calibrating autoexposure:
```
Turned on camera regulator
Camera started successfully
Calibrating Auto Exposure...
Turned on camera regulator
Camera started successfully
Calibrating Auto Exposure...
```
At this point it just hangs.

**Comment by KidA-88** [comment]
This topic has been resolved yes and no:)

I ordered right away two HM01b0 cameras with the Edge board. Simply trying out the other model resolved the problem for me. From the error code I received, I figured it had something to do with the model ID. Could it be that some camera models are simply not properly configured? 

So, generally speaking the issue has not been resolved.

**Comment by taunoe** [comment]
I had the same issue with Sparkfun Edge + Himax HM01B0 Camera. Spent the whole day unsuccessfully. Then the next day I decided to try it one more time and it miraculously started to work. Same hardware and code ...
